name: Get Diff as Single String

on:
  push:
    branches:
      - main  # You can change this to the branch you're interested in

jobs:
  capture-diff-stat:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        run: |
          git clone https://github.com/hanzla-spec/microservices.git repo
          git checkout poc
          git diff --name-only origin/poc >> target.txt