name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.abc.outputs.all }}"

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Run
        run: echo $(python3 scripts/script.py ${{ steps.abc.outputs.all }})
