name: Get Diff as Single String

on:
  push:
    branches:
      - main  # You can change this to the branch you're interested in

jobs:
  capture-diff-stat:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        run: |
          git clone https://github.com/hanzla-spec/microservices.git
          cd microservices
          git checkout main
          git diff --name-only origin/main >> target.txt

          # Ensure the file exists
          if (Test-Path 'target.txt') {
            # Read and display the contents of the file
            $CONTENTS = Get-Content 'target.txt' -Raw
            Write-Host "Contents of target.txt: $CONTENTS"
          }
          else {
            Write-Host "target.txt not found"
          }
        
      - name: clear
        run: rmdir microservices

