name: Get Diff as Single String

on:
  push:
    branches:
      - main  # You can change this to the branch you're interested in

jobs:
  capture-diff-stat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest changes from remote
        run: git fetch origin main

      - name: Get diff stat as single string
        id: diff-stat
        run: |
          # Get the diff stat and convert to a single string
          DIFF_STAT=$(git diff --name-only origin/main | tr '\n' ' ')
          echo "$DIFF_STAT"