name: Check Changed Files

on:
  push:
    branches:
      - main

jobs:
  get-changed-files:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        run: |
          # Get the list of changed files
          git diff --name-only HEAD~1 HEAD > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt
          echo "::set-output name=files::$(cat changed_files.txt)"

      - name: Use changed files
        run: |
          echo "The changed files are:"
          echo "${{ steps.changed-files.outputs.files }}"
