name: Capture Git Diff to Space-Separated Variable

on:
  push:
    branches:
      - main

jobs:
  capture-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Capture Git Diff to Space-Separated Variable
        run: |
          # Get the commit hashes for before and current commit
          BEFORE_COMMIT=${{ github.event.before }}
          CURRENT_COMMIT=${{ github.sha }}

          # Run the git diff command and store the changed files in a space-separated variable
          git diff --name-only $BEFORE_COMMIT $CURRENT_COMMIT > target.txt

          output=$(cat target.txt | tr '\n' ' ')

          # Output the changed files to the log
          echo "$output"
