name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main)
          echo "Changed files: $CHANGED_FILES"
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Display changed files
        run: echo "The following files were changed ${{ steps.detect-changed-files.outputs.changed_files }}"

