name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: abc1
        uses: actions/checkout@v2.1.0
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Printing
        run: |
          git diff --name-only origin/${{ github.ref }}...HEAD > changedfiles.txt
          cat changedfiles.txt

          echo $(python3 scripts/script.py "${{ github.ref }}" "${{ steps.abc.outputs.all }}")
