name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: tj-actions/checkout@v3

      - name: Get Changed Files
        uses: tj-actions/changed-files@v21
        id: changed-files

      - name: Display Changed Files
        run: echo "Changed files: ${{ steps.changed-files.outputs.files }}"

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      -name: Run
        run: echo $(python3 scripts/script.py ${{ steps.changed-files.outputs.files }})
