name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-changes:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: tj-actions/checkout@v3

      - name: Get Changed Files
        uses: tj-actions/changed-files@v21
        id: changed-files

      - name: Display Changed Files
        run: echo "Changed files: ${{ steps.changed-files.outputs.files }}"

      - name: Commit Changes
        uses: tj-actions/commit-changes@v7
        with:
          commit_message: "Auto-commit changes"
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
